project:
  type: website
  output-dir: _site

website:
  title: "GIS Group 6: Pavement vs Peat"
  navbar:
    left:
      - href: index.qmd
        text: Abstract
      - href: scope.qmd
        text: Project Scope
      - href: data.qmd
        text: Data Analysis
      - href: methodology.qmd
        text: Methodology
      - href: webmaps.qmd
        text: Web Maps
      - href: lessons.qmd
        text: Recommendations & Lessons
      - href: poster.qmd
        text: Poster
      - href: about.qmd
        text: Team

      

format:
  html:
    theme:
      - cerulean
      - brand
    css: styles.css
    toc: true

editor: visual

