project:
  type: website

website:
  title: "GIS Group 6: Pavement vs Peat"
  navbar:
    left:
      - href: Overview.qmd
        text: Abstract
      - href: scope.qmd
        text: Project Scope
      - href: data.qmd
        text: Data Preparation
      - href: index.qmd
        text: Methodology
      - href: ""
        text: Results & Discussion
      - href: ""
        text: Web Maps
      - href: ""
        text: Lesson Learnt
      - href: ""
        text: Poster
      - href: about.qmd
        text: Team

      

format:
  html:
    theme:
      - cerulean
      - brand
    css: styles.css
    toc: true

editor: visual

