project:
  type: website

website:
  title: "GIS Group 6: Pavement vs Peat"
  navbar:
    left:
      - href: Overview.qmd
        text: Abstract
      - href: ""
        text: Methodology
      - href: ""
        text: Results and Discussion
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Team
      

format:
  html:
    theme:
      - cerulean
      - brand
    css: styles.css
    toc: true

editor: visual

