project:
  type: website

website:
  title: "SMT201-GISProject"
  navbar:
    left:
      - href: ""
        text: Overview
      - href: ""
        text: Methodology
      - href: ""
        text: Results and Discussion
    right: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Team
      

format:
  html:
    theme:
      - morph
      - brand
    css: styles.css
    toc: true

editor: visual

