---
title: "Pavement vs Peat"
authors: "Anne Saphrin Alex Sathyan, Harshitha Balaji, Lau Liang Jun"
date: "April 6, 2025"
date-modified: "last-modified"
---

# Abstract

Beyond Singapore, other south-east asian countries have been undergoing rapid urbanisation and development in order to propel economic growth. Namely, Malaysia’s **Kuala Lumpur (“KL”)** has been on the rise in terms of urbanisation and consequently, this has led to a greater proclivity to natural disasters such as landslides and flash floods due to environmental degradation. Studies show that Malaysia has been extremely prone to landslide occurrences and is the 10th country with the highest frequency of landslides. Currently, KL has been the greatest contributor to this figure in Malaysia given its rapid urbanisation. 

Therefore, we are interested in analysing the effects of landslides and any accompanying phenomena such as flash floods on the changes in land cover that have occurred in KL over the span of 5 years (2020 to 2024). 

In this project, we have utilised Sentinel-2 satellite imagery data obtained from Copernicus to perform remote sensing by means of image processing and classification techniques. Additionally, we sourced our vector layers and baseline land cover information from OpenStreetMap (OSM) and delineated sub-regions within KL using Mukim boundary layers for further specific analysis. 

After creating any and all layers, we defined 8 different land classes (Natural Vegetation, Managed Vegetation, Water Body, Impervious Surfaces, Built-Up (low-rise buildings), Built-Up (high-rise buildings), Barren Land, Shadow). We then obtained the necessary training and testing samples from these land classes to perform classification using the Semi-Classification Plugin (SCP) and observe changes in specific land classes (Natural Vegetation, Managed Vegetation, Water Body, Impervious Surfaces, Built-Up (low-rise buildings), Barren Land). 

From our classification and subsequent observations, we were able to find the following: 

1.  There was an overall increasing trend in Managed Vegetation composition.

2.  There was an overall decreasing trend in Natural Vegetation as well as Impervious Surfaces composition.

3.  There was considerable variation in Barren Land and Water Bodies composition.

Notably, we observed sharp increases and decreases in the different land classes from 2023 to 2024, which we believe can be attributed to a major landslide that occurred in Bukit Tunku, KL in April 2023. The overall results also allowed us to observe the varying levels of accuracies across the years, with 2024 having the greatest classification accuracy (Overall Accuracy = 81.3%, Kappa Hat = 0.759) and 2022 having the lowest classification accuracy (Overall Accuracy = 40.4%, Kappa Hat = 0.286). We will dive deeper into our observations and takeaways in the following sections of the report. 

\
