---
title: "Pavement vs Peat"
authors: "Anne Saphrin Alex Sathyan, Harshitha Balaji, Lau Liang Jun"
date: "April 6, 2025"
date-modified: "last-modified"
---

# 6.0 Limitations

Throughout this project, we faced many limitations:

1.  **Lack of sufficient, accurate information:** We struggled with finding vector layer data that represented the KL region accurately and the data that we could find was quite pixelated, blurry and did not fit the actual geographical boundaries of the state within Malaysia precisely enough. Beyond this, we also struggled to find sufficient information on the actual number of landslides that occurred in Malaysia/KL due to faults in reporting, inaccessible reports (paywalled/requires special access) as well as language barriers.

2.  **Classification troubles:** Given the type of data we were working with, we struggled to obtain accurate classification values. Some of the vector layer imaging that we used were not sufficiently detailed and often had blurry, pixelated visualisation, which meant that the SCP plugin was more likely to classify ROI polygons belonging to certain land classes into the wrong land classes. For example, the SCP plugin struggled very much with distinguishing between ROI polygons originally selected from roads (Impervious Surfaces) and polygons selected from rivers (Water Bodies), which meant that our accuracy values specifically for those land classes were greatly affected across the years.

# 7.0 Recommendations

Given the data we have analysed, the trends we have observed and the conclusions we have drawn, we believe that the following would be apt recommendations to ensure that the likelihood of landslides are reduced and environmental risks are mitigated while balancing the need for urbanisation: 

1.  To stop landslides and degradation, stricter rules should be implemented for construction in high-risk slopes and sensitive hilly areas.

2.  In order to preserve slope stability and natural drainage, forest conservation initiatives should place a high priority on protecting and restoring forests, particularly those that are close to urbanising areas.

3.  To control excessive rainfall and lessen flooding, landslide-prone communities need to upgrade their infrastructure and urban drainage systems. Furthermore, integrating geospatial monitoring tools like GIS and remote sensing into urban planning will aid in the early detection of land deterioration. 

4.  Since they will support both urban growth and environmental resilience, sustainable urban green initiatives like urban forests and green roofs should be encouraged.

# 8.0 Future Work

We believe that our current project is quite limited for us to conclude anything concrete about the relationship between landslides and land cover change due to the restricted level of analysis that has been conducted. To expand on this issue and further the understanding on our chosen topic, we believe the following changes can be implemented in future works:

1.  **Wider Study Area:** In order to evaluate the wider impacts of urbanisation, floods, and landslides on land cover, include nearby areas of Kuala Lumpur such as Selangor (e.g., Putrajaya, Petaling Jaya) which have more hilly terrain.

2.  **Use Multi-source Data:** Combine information such as infrastructure development or population density to have a better understanding of the factors influencing change, or use terrain analysis (slope) to predict and pinpoint vulnerable regions at risk of landslides, using data obtained from past landslides, such as the Bukit Tunku case.

3.  **Extend Temporal Analysis:** To enhance environmental effect forecasts, we could look to extend the study period to examine long-term trends (by investigating barren land used for land development projects and how surrounding land cover has changed before and after, to predict the possibility of landslides ) or carry out seasonal monitoring by tracking monsoon-driven changes using quarterly composites. \

\
